plugins {
    id 'java'
}

group = 'org.digitalgenesis'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("org.json:json:20220924")
    implementation('commons-io:commons-io:2.14.0')
    implementation("commons-codec:commons-codec:1.15")
    implementation("com.microsoft.azure:msal4j:1.14.0")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}